import json, os, re, sys
from datetime import datetime, timedelta, timezone
IST=timezone(timedelta(hours=5,minutes=30))
now=datetime.now(IST)
date=(now.date()+timedelta(days=int(os.getenv("DAY_OFFSET","0"))))
topics=[
("ai-context","Why AI Needs Context to Give Better Answers","AI can produce very different answers from the same short request because context changes what the model should optimize for. Clear goals, constraints, examples, and audience details reduce ambiguity. That does not make every answer correct, so important claims still need verification. Better prompts are less about magic words and more about giving useful context.",["Vague prompt → many possibilities","Context narrows the task","Verify important claims"],"ai verification chat"),
("compound-interest","Why Compound Growth Feels Slow at First","Compound growth looks unimpressive early because gains are being applied to a small base. Over longer periods, previous gains can also generate gains, making the curve steeper. The same mathematics can apply to savings, debt, audiences, and repeated improvements. The key lesson is that rate and time both matter, and real returns are never guaranteed.",["Small base → small gains","Growth builds on prior growth","Time changes the curve"],"money growth graph"),
("doorway-effect","Why You Forget After Walking Into Another Room","Researchers use the term doorway effect for situations where crossing an event boundary can make a recent intention harder to retrieve. A change of context may cause the brain to update what it is actively tracking. The effect is not universal, but it helps explain why returning to the previous context can sometimes remind you what you wanted.",["An intention is active","Context suddenly changes","Returning can cue memory"],"brain doorway memory"),
("lightning-hot","Lightning Can Be Hotter Than the Sun's Surface","A lightning channel can briefly heat the surrounding air to temperatures several times hotter than the surface of the Sun. That intense heating makes air expand rapidly, producing the shock wave we hear as thunder. The comparison is about temperature, not total energy: the Sun is vastly larger and continuously produces enormous power.",["Lightning heats air rapidly","Expanding air creates thunder","Temperature ≠ total energy"],"lightning sun storm"),
("roman-concrete","Why Some Ancient Roman Concrete Lasted So Long","Some Roman marine concrete survived for centuries because its chemistry differs from many modern mixes. Researchers have studied volcanic materials, lime-rich components, and reactions with seawater that can form durable minerals. That does not mean every Roman structure was indestructible, but surviving examples reveal useful material-science lessons.",["Different ancient chemistry","Minerals can form over time","Survivors teach material science"],"roman concrete architecture"),
("octopus-blue","Why Octopus Blood Is Blue","Octopuses use a copper-containing oxygen transport protein called hemocyanin rather than the iron-rich hemoglobin humans use. Oxygenated hemocyanin appears blue. It can work effectively in cold, low-oxygen marine conditions, helping these animals transport oxygen through very different environments from ours.",["Humans use hemoglobin","Octopuses use hemocyanin","Copper chemistry looks blue"],"octopus ocean biology"),
("confirmation-bias","How Confirmation Bias Changes What We Notice","Confirmation bias describes a tendency to seek, notice, or interpret information in ways that support an existing belief. It can affect everyone, especially when a topic feels important. One practical countermeasure is to deliberately ask what evidence would change your mind and then examine credible information that challenges your first conclusion.",["Belief shapes attention","Supporting evidence feels easier","Seek disconfirming evidence"],"brain evidence psychology"),
("qr-code","Why QR Codes Can Still Work When Damaged","QR codes include error-correction information. Depending on the correction level and where damage occurs, software can reconstruct missing portions and still decode the message. That is why some QR designs can include small logos or survive scratches. Damage is not unlimited, though; enough missing critical data will make the code unreadable.",["Data includes redundancy","Software reconstructs parts","Too much damage still fails"],"qr pixels technology"),
("airplane-windows","Why Airplane Windows Are Rounded","Early pressurized aircraft helped engineers learn that sharp corners can concentrate stress. Modern passenger windows use rounded shapes so loads flow more smoothly through the fuselage structure. The window is only one part of a carefully engineered pressure vessel, but avoiding sharp corners helps reduce dangerous stress concentrations.",["Cabin pressure loads fuselage","Sharp corners concentrate stress","Curves distribute load better"],"airplane window engineering"),
("barcode","The Hidden Logic Behind a Barcode","A barcode converts an identifier into patterns of dark and light spaces that scanners can read. The code usually points to database information rather than storing an entire product description itself. Check digits and standardized structures help detect reading errors, turning a simple printed pattern into a reliable link between physical items and digital records.",["Bars encode an identifier","Scanner reads spacing","Database supplies the details"],"barcode scanner retail"),
("moon-footprints","Why Apollo Footprints Can Last So Long","The Moon has no weather like Earth's rain and wind, so footprints left in lunar soil are not quickly erased by those processes. Micrometeorite impacts and other space-weathering effects can alter the surface over very long periods, so the prints are not literally permanent. They can nevertheless persist far longer than footprints on Earth.",["No rain or wind","Tracks are not quickly erased","Space weathering is very slow"],"moon astronaut footprint"),
("glass-liquid","Old Glass Is Not Slowly Flowing Downward","Old windows are sometimes thicker at the bottom, leading to the claim that glass flows like a very slow liquid. At ordinary temperatures, glass behaves as an amorphous solid. Uneven thickness in historic panes largely reflects old manufacturing methods and installation choices, not centuries of glass visibly sagging under gravity.",["Old panes can be uneven","Glass is an amorphous solid","Manufacturing explains thickness"],"glass window science"),
("wifi-name","What Wi-Fi Actually Means","Wi-Fi is a trademarked name used for wireless networking products based on IEEE 802.11 standards. A popular myth says the name is short for wireless fidelity, but the Wi-Fi Alliance has explained that it was created as a brand name rather than a technical acronym. The familiar term is marketing wrapped around complex radio standards.",["IEEE 802.11 is technical","Wi-Fi is the brand name","Not a technical acronym"],"wifi radio technology"),
("sleep-learning","Can You Really Learn New Facts While Sleeping?","Sleep is important for consolidating memories formed while awake, but that is different from reliably learning complex new material while unconscious. Some experiments find limited effects for simple associations or cues during sleep. For practical learning, studying while awake and then getting sufficient sleep remains much better supported.",["Study while awake","Sleep helps consolidation","Complex sleep-learning is limited"],"sleep brain learning"),
("currency-paper","Why Banknotes Are Harder to Copy Than They Look","Modern banknotes combine multiple security features such as specialized substrates, fine printing, color-shifting elements, transparent windows, watermarks, and machine-readable features. Different currencies use different combinations. The goal is not to make copying physically impossible, but to make convincing counterfeits difficult and verification relatively easy.",["Many security layers","Some visible, some machine-readable","Verification is designed in"],"banknote security money"),
("elevator-button","What the Door-Close Button Really Does","The behavior of elevator door-close buttons varies by building, control system, operating mode, and local accessibility rules. In some passenger situations the button may have little immediate effect, while authorized or special modes can behave differently. So the claim that every door-close button is fake is too broad—the correct answer depends on the system.",["Behavior varies by system","Accessibility timing matters","Not every button is fake"],"elevator button building"),
("shark-senses","How Sharks Detect More Than Just Smell","Sharks combine several senses while hunting and navigating. Along with smell, they detect vibrations and water movement, and specialized ampullae of Lorenzini can sense weak electric fields produced by living organisms. Different shark species rely on these abilities differently, making their sensory world much richer than the common smell-only stereotype.",["Smell is only one signal","Water movement adds information","Electroreception detects weak fields"],"shark ocean senses"),
("placebo","Why Expectations Can Affect Symptoms","Placebo effects show that expectations and treatment context can influence some symptoms and measured outcomes, especially subjective experiences such as pain. They do not mean a person imagined an illness, nor do placebos cure every disease. Researchers study these effects to understand how brain, body, expectations, and clinical context interact.",["Expectation can influence experience","Effects vary by outcome","Not a cure-all"],"brain placebo medical research"),
("cloud-weight","Clouds Can Weigh Hundreds of Tons","A cloud looks light because tiny droplets are spread through a huge volume of air. Adding the mass of all that liquid water can produce surprisingly large totals, often hundreds of tons for a modest cumulus cloud. The droplets remain suspended because they are tiny and because moving air helps support them.",["Tiny droplets are dispersed","Huge volume adds up","Air currents help suspend them"],"cloud weather water"),
("keyboard-qwerty","Why QWERTY Became the Keyboard Standard","QWERTY originated with nineteenth-century typewriters and evolved through early machine designs and business adoption. Its survival is not explained by one simple story about intentionally slowing typists. Once manufacturers, training, workplaces, and users standardized around the layout, switching costs helped make QWERTY remarkably persistent.",["Born in typewriter era","Adoption created familiarity","Standards can become sticky"],"keyboard qwerty history"),
("ocean-pressure","Why the Deep Ocean Can Crush Equipment","Water pressure increases with depth because deeper objects support the weight of more water above them. At great ocean depths, external pressure becomes enormous, so submarines, sensors, and housings need shapes and materials designed to resist collapse. Deep-sea engineering is therefore as much about pressure management as it is about waterproofing.",["Pressure rises with depth","Deep equipment faces huge loads","Shape and material matter"],"submarine deep ocean"),
("memory-reconstruction","Your Memory Is More Like Reconstruction Than Replay","Human memory is not a perfect video recording. When we remember an event, the brain reconstructs details using stored information, context, and later knowledge. That process is useful but can introduce errors. Confidence and accuracy are not identical, which is why careful records and independent evidence matter when details are important.",["Memory stores information","Recall reconstructs the event","Confidence ≠ perfect accuracy"],"brain memory reconstruction"),
("gps-relativity","GPS Needs Relativity to Stay Accurate","GPS satellites carry precise clocks, and relativity affects how those clocks run compared with clocks on Earth. Engineers account for both motion-related and gravity-related timing differences. Without these corrections, positioning errors would accumulate quickly. A theory that sounds abstract therefore plays a practical role in everyday navigation.",["Satellites carry atomic clocks","Motion and gravity affect timing","Corrections keep positions accurate"],"satellite gps relativity"),
("fridge-light","How Your Fridge Knows the Door Is Closed","Many refrigerators use a small switch, magnetic sensor, or electronic door sensor to detect whether the door is open. That signal can control the interior light and may also influence alarms or cooling behavior. You can often find the switch near the frame, although newer designs may hide the sensor completely.",["Door changes sensor state","Controller switches the light","Newer sensors may be hidden"],"refrigerator sensor technology")
]
longs=[
("1030","How AI Systems Actually Produce Answers — And Where They Go Wrong","AI & Technology"),
("1530","7 Psychology Effects That Quietly Shape Everyday Decisions","Psychology"),
("2030","10 Science Facts That Sound Fake but Have Real Explanations","Science")
]
def short_job(hour,t):
 slug,title,script,scenes,visual=t
 key=f"{date:%Y%m%d}-{hour:02d}00-{slug}"
 return {"job_key":key,"title":title+" #Shorts","description":"A concise educational explainer. #Shorts","script":script,"scenes":[{"text":x,"visual":visual} for x in scenes],"category_id":"27","tags":["Shorts","facts","education",slug.replace("-"," ")]}
os.makedirs("jobs",exist_ok=True)
short_hours=list(range(0,24,2))
for i,h in enumerate(short_hours):
 t=topics[(i + date.toordinal()) % len(topics)]
 p=f"jobs/{date:%Y%m%d}-{h:02d}00-{t[0]}.json"
 if not os.path.exists(p): json.dump(short_job(h,t),open(p,"w"),indent=2,ensure_ascii=False)
os.makedirs("longform/jobs",exist_ok=True)
baseparas=[
"Start with the central idea and separate what the technology can do from what people often assume it can do. Modern AI language systems learn statistical patterns from large collections of examples. When asked a question, they generate a response piece by piece using those learned patterns and the context supplied in the prompt. Fluency is therefore not the same thing as verification. A confident sentence can still contain an error. Useful practice is to provide clear context, ask for sources when appropriate, and independently verify decisions that matter.",
"Everyday decisions are influenced by attention, memory, framing, expectations, social information, and habits. Psychology gives names to some recurring patterns, but these are tendencies rather than rules that control every person. Confirmation bias can make supporting evidence easier to notice. Framing can change how equivalent choices feel. Availability can make vivid examples seem more common. Anchoring can pull estimates toward an initial number. Understanding these effects is most useful when it encourages slower checking rather than simplistic mind-reading.",
"Science becomes memorable when a surprising claim is paired with the mechanism behind it. Lightning can briefly heat air beyond the temperature of the Sun's visible surface, but temperature is not the same as total energy. Clouds can contain enormous masses of liquid water because tiny droplets are distributed through huge volumes. GPS depends on relativistic clock corrections. Deep-ocean machines need to resist immense pressure. Each example becomes less mysterious once scale, measurement, and mechanism are explained."
]
for i,(tm,title,cat) in enumerate(longs):
 key=f"{date:%Y%m%d}-{tm}-long-{cat.lower().replace(' & ','-').replace(' ','-')}"
 # Build a genuinely long narration from structured sections, not a repeated one-line clip.
 sections=[]
 for n in range(1,10):
  sections.append(f"Section {n}. "+baseparas[i]+" The practical takeaway from this section is to distinguish the memorable headline from the evidence and mechanism behind it. Examples are useful starting points, but context determines whether a general principle applies to a particular case.")
 script=" ".join(sections)
 chapters=[{"title":f"{cat.upper()} • PART {n}","onscreen":("Mechanism • Evidence • Context\n"+title)} for n in range(1,10)]
 job={"job_key":key,"title":title,"series":"Daily Growth Video","description":f"An educational deep dive into {cat.lower()}.","script":script,"chapters":chapters,"category_id":"27","tags":[cat,"education","explainer"]}
 p=f"longform/jobs/{date:%Y%m%d}-{tm}.json"
 if not os.path.exists(p): json.dump(job,open(p,"w"),indent=2,ensure_ascii=False)
print("GENERATED",date,12,"shorts",3,"longform")
